### ISSUE TITLE
non optional wantKeepAlive feature [BUG]

### ISSUE THREAD

**Issue by Carlit0** [bluefireteam/photo_view#478]
**Describe the bug**
The feature to keep the (scale) state of an image was introduced in #452 (release 0.13.0) with **wantKeepAlive => true**.
The feature is definitely useful but should be optional!
It causes unwanted behavior, for everyone who wants to mimic the iOS Photo app.

**Which versions of Flutter/Photo View, and which browser / OS are affected by this issue? Did this work in previous versions of Photo View?**
release 0.13.0

**Comment by ToniTornado** [comment]
I don't know what you describe as "unwanted behavior" but for us this unwanted behavior includes app crashes on the lowest level because it runs out of memory. The default behavior introduced in 0.13.0 keeps all PhotoViews alive until memory is full. Given a gallery that a user can swipe through, this limit is reached after ~40 images on the latest hardware. This should be fixed by this PR so +1 to finally merge it into a 0.14.0 👍🏻

**Comment by Carlit0** [comment]
Interesting bug @ToniTornado !
To explain, when you swipe through photos in the iOS Photos app, the Photos app does not maintain the scaling state.
I think the Android Gallery app behaves the same way.

My fork would be a workaround for now:
`photo_view:
    git:
      url: git://github.com/Carlit0/photo_view.git
      ref: master`

**Comment by ToniTornado** [comment]
I first went with version 0.12.0 but now use your fork instead. The fix for flashing background color implemented in 0.13.0 was too noticeable so thanks for pointing me to it!

**Comment by Carlit0** [comment]
FYI: as soon as a new version is published i will delete my fork @ToniTornado
